package az.fitnest.gateway;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.client.discovery.EnableDiscoveryClient;

import org.springframework.cloud.gateway.route.RouteLocator;
import org.springframework.cloud.gateway.route.builder.RouteLocatorBuilder;
import org.springframework.context.annotation.Bean;

@SpringBootApplication
public class ApiGatewayApplication {
        // Trigger CI/CD rebuild and deployment to expose new reservation admin endpoints

        @Bean
        public RouteLocator customRouteLocator(RouteLocatorBuilder builder) {
                return builder.routes()
                        .route("identity-backend", r -> r.path(
                                        "/api/v1/identity/me",
                                        "/api/v1/me/change-email/request",
                                        "/api/v1/me/change-email/confirm",
                                        "/api/v1/me/change-mobile/request",
                                        "/api/v1/me/change-mobile/confirm",
                                        "/api/v1/me/change-password",
                                        "/api/v1/me/delete-account",
                                        "/api/v1/me/change-email/resend",
                                        "/api/v1/me/change-mobile/resend",
                                        "/api/v1/auth/login",
                                        "/api/v2/auth/login",
                                        "/api/v3/auth/login",
                                        "/api/v3/auth/login/verify",
                                        "/api/v3/auth/login/check",
                                        "/api/v2/auth/social/google",
                                        "/api/v2/auth/social/apple",
                                        "/api/v2/auth/social/google/login/add-number/otp/request",
                                        "/api/v2/auth/social/apple/login/add-number/otp/request",
                                        "/api/v2/auth/social/google/login/add-number/otp/verify",
                                        "/api/v2/auth/social/apple/login/add-number/otp/verify",
                                        "/api/v2/auth/registration/register/complete",
                                        "/api/v3/auth/registration/register",
                                        "/api/v3/auth/registration/register/complete",
                                        "/api/v1/auth/refresh",
                                        "/api/v2/auth/refresh",
                                        "/api/v3/auth/refresh",
                                        "/api/v1/auth/logout",
                                        "/api/v1/auth/social/apple",
                                        "/api/v1/auth/social/google",
                                        "/api/v1/auth/registration/register",
                                        "/api/v1/auth/registration/register/complete",
                                        "/api/v1/auth/password-recovery/forgot-password",
                                        "/api/v1/auth/password-recovery/reset-password",
                                        "/api/v1/auth/password-recovery/admin/forgot-password",
                                        "/api/v1/auth/password-recovery/admin/reset-password",
                                        "/api/v1/auth/otp/verify",
                                        "/api/v1/auth/otp/registration/register/resend",
                                        "/api/v1/legal/privacy-policy",
                                        "/api/v1/legal/terms-of-use",
                                        "/api/v1/public/landing/privacy-policy",
                                        "/api/v1/public/landing/terms-of-use",
                                        "/api/v1/legal/consents/me",
                                        "/api/v1/admin/legal/documents",
                                        "/api/v1/admin/legal/documents/{id}",
                                        "/api/v1/admin/legal/documents/{id}/activate",
                                        "/api/v1/admin/legal/documents/{id}/deactivate",
                                        "/api/v1/admin/legal/consents",
                                        "/api/v1/admin/users/{userId}/role",
                                        "/api/v1/admin/users/{userId}/hard-delete",
                                        "/api/v1/admin/users/{userId}/device-limit/reset",
                                        "/api/v1/admin/users/device-limit/reset-all",
                                        "/api/v1/admin/users/rate-limit/reset",
                                        "/api/v1/admin/users/otp-rate-limit/reset",
                                        "/api/v1/admin/users/otp-rate-limit/reset-all",
                                        "/api/v1/admin/users/{userId}/block",
                                        "/api/v1/admin/users/{userId}/unblock",
                                        "/api/v1/admin/users/{userId}/password/reset",
                                        "/api/v1/admin/users/{userId}/change-role",
                                        "/api/v1/admin/roles",
                                        "/api/v1/admin/roles/{roleId}",
                                        "/api/v1/internal/users/{userId}",
                                        "/api/v1/internal/users/{userId}/profile-image",
                                        "/api/v1/internal/users/{userId}/setup-required",
                                        "/api/v1/internal/users/{userId}/language",
                                        "/api/v1/internal/users/{userId}/session-status")
                                .uri("http://identity-backend:8080"))

                        .route("catalog-backend", r -> r.path(
                                "/api/v1/admin/reports/app-qr-scans",
                                "/api/v1/public/app-qr/scan/light",
                                "/api/v1/public/app-qr/scan/dark",
                                "/api/v1/public/landing/stats",
                                "/api/v1/public/landing/home/gyms",
                                "/api/v1/public/landing/home/stores",
                                "/api/v1/public/landing/gyms",
                                "/api/v1/public/landing/gyms/{gymId}",
                                "/api/v1/public/landing/stores",
                                "/api/v1/public/landing/stores/{storeId}",
                                "/api/v1/public/landing/media/{fileId}",
                                "/api/v1/admin/reports/qr-scans",
                                "/api/v1/admin/reports/gym-payments",
                                "/api/v1/admin/stores",
                                "/api/v1/admin/stores/{id}",
                                "/api/v1/admin/stores/step1",
                                "/api/v1/admin/stores/{id}/step2",
                                "/api/v1/admin/stores/{id}/step3",
                                "/api/v1/admin/stores/validate/step1",
                                "/api/v1/admin/stores/validate/step2",
                                "/api/v1/admin/stores/validate/step3",
                                "/api/v1/admin/stores/{id}",
                                "/api/v1/admin/stores/{id}/logo",
                                "/api/v1/admin/stores/{id}/cover",
                                "/api/v1/admin/stores/{id}/discounts",
                                "/api/v1/admin/stores/{storeId}/image",
                                "/api/v1/admin/stores/all",
                                "/api/v1/admin/stores/{id}/status",
                                "/api/v1/admin/stores/list",
                                "/api/v1/admin/gyms/list",
                                "/api/v1/admin/gyms",
                                "/api/v2/gyms",
                                "/api/v2/gyms/{gymId}",
                                "/api/v3/gyms/{gymId}",
                                "/api/v2/admin/gyms/step1",
                                "/api/v2/admin/gyms/validate/step1",
                                "/api/v2/admin/gyms/{id}/step5",
                                "/api/v2/admin/gyms/validate/step5",
                                "/api/v2/admin/gyms/{id}/step6",
                                "/api/v2/admin/gyms/validate/step6",
                                "/api/v2/admin/gyms/{id}/subscriptions",
                                "/api/v2/admin/gyms/{id}/details",
                                "/api/v2/admin/gyms/{id}/trainers",
                                "/api/v2/admin/gyms/create-complete",
                                "/api/v1/admin/gyms/step1",
                                "/api/v1/admin/gyms/create-complete",
                                "/api/v1/admin/gyms/{id}/step2",
                                "/api/v1/admin/gyms/{id}/step3",
                                "/api/v1/admin/gyms/{id}/step4",
                                "/api/v1/admin/gyms/{id}/step5",
                                "/api/v1/admin/gyms/{id}/step6",
                                "/api/v1/admin/gyms/{id}/step7",
                                "/api/v1/admin/gyms/validate/step1",
                                "/api/v1/admin/gyms/validate/step2",
                                "/api/v1/admin/gyms/validate/step3",
                                "/api/v1/admin/gyms/validate/step4",
                                "/api/v1/admin/gyms/validate/step5",
                                "/api/v1/admin/gyms/validate/step6",
                                "/api/v1/admin/gyms/validate/step7",
                                "/api/v1/admin/gyms/services",
                                "/api/v1/admin/gyms/services/{id}",
                                 "/api/v1/admin/gyms/history",
                                 "/api/v1/admin/gyms/{id}/history",
                                 "/api/v1/admin/gyms/{id}/packages/{packageId}/history",
                                 "/api/v1/admin/gyms/{id}/analytics",
                                "/api/v1/admin/gyms/{id}/details",
                                "/api/v1/admin/gyms/{id}/work-hours",
                                 "/api/v1/admin/translations",
                                 "/api/v1/admin/translations/bulk",
                                 "/api/v1/admin/translations/{id}",
                                "/api/v1/admin/gyms/{id}",
                                "/api/v1/admin/gyms/{id}/qr",
                                "/api/v1/admin/gyms/{id}/subscriptions",
                                "/api/v1/admin/gyms/{id}/subscriptions/{subscriptionId}",
                                "/api/v1/admin/gyms/{id}/subscriptions/enable",
                                "/api/v1/admin/gyms/{id}/subscriptions/{planId}/benefits",
                                "/api/v1/admin/professions/{id}",
                                "/api/v1/admin/professions",
                                "/api/v1/admin/professions/all",
                                "/api/v1/professions",
                                "/api/v1/professions/{id}",
                                "/api/v1/admin/gyms/{id}/rooms",
                                "/api/v1/admin/gyms/{id}/rooms/{roomId}",
                                "/api/v1/admin/gyms/{id}/rooms/{roomId}/name",
                                "/api/v1/admin/gyms/{id}/rooms/images/{imageId}",
                                "/api/v1/admin/gyms/{id}/trainers",
                                "/api/v1/admin/gyms/{id}/trainers/{trainerId}",
                                "/api/v1/admin/gyms/{id}/trainers/{trainerId}/photo",
                                "/api/v1/admin/gyms/{id}/admins",
                                "/api/v1/admin/gyms/{id}/admins/{adminId}",
                                "/api/v1/admin/gyms/{id}/reviews",
                                "/api/v1/admin/gyms/reviews/{reviewId}",
                                "/api/v1/admin/gyms/reviews/pending",
                                "/api/v1/admin/gyms/reviews/{reviewId}/approve",
                                "/api/v1/admin/gyms/reviews/{reviewId}/reject",
                                "/api/v1/admin/gyms/{id}/status",
                                "/api/v1/admin/gyms/{id}/cover",
                                "/api/v1/admin/gyms/{id}/lesson-hours",
                                "/api/v1/admin/gyms/{id}/lesson-hours/archive",
                                "/api/v1/admin/gyms/lesson-hours/{lessonHourId}",
                                "/api/v1/admin/gyms/lesson-hours/{lessonHourId}/reservation-counts",
                                "/api/v1/admin/gyms/{id}/reservations",
                                "/api/v1/admin/gyms/{id}/reservations/stats",
                                "/api/v1/admin/gyms/reservations/{reservationId}",
                                "/api/v1/admin/gyms/reservations/{reservationId}/status",
                                "/api/v1/admin/gyms/users/{userId}/qr-history",
                                "/api/v1/admin/gyms/geocoding/reverse",
                                "/api/v1/admin/gyms/geocoding/forward",
                                "/api/v1/admin/gyms/all",
                                "/api/v1/admin/reservations",
                                "/api/v1/admin/reservations/gyms/{id}/enable",
                                "/api/v1/admin/reservations/gyms/{id}/trainers/{trainerId}/enable/{lessonId}",
                                "/api/v1/admin/reservations/gyms/{id}/trainers/{trainerId}/lessons/{lessonId}/availabilities",
                                "/api/v1/admin/reservations/{reservationId}/status",
                                "/api/v1/admin/reservations/{reservationId}/approve",
                                "/api/v1/admin/reservations/{reservationId}/reject",
                                "/api/v1/admin/reservations/gyms/{id}/lesson-types",
                                "/api/v1/admin/reservations/gyms/{id}/lesson-types/{lessonTypeId}",
                                "/api/v1/admin/reservations/gyms/{gymId}/categories/{categoryId}/lessons/{lessonId}/rules",
                                "/api/v1/admin/reservations/gyms/{gymId}/rules",
                                "/api/v1/admin/reservations/cancel-reasons",
                                "/api/v1/admin/reservations/cancel-reasons/{code}",
                                "/api/v1/admin/categories",
                                "/api/v1/admin/categories/all",
                                "/api/v1/admin/categories/{id}",
                                "/api/v1/admin/categories/{categoryId}/name",
                                "/api/v1/admin/categories/{categoryId}/photo",
                                "/api/v1/admin/categories/{categoryId}/icon",
                                "/api/v1/admin/lesson-types",
                                "/api/v1/admin/lesson-types/{id}",
                                "/api/v1/categories",
                                "/api/v1/gyms/{gymId}",
                                "/api/v1/gyms/{gymId}/images",
                                "/api/v1/gyms/{gymId}/qr",
                                "/api/v1/gyms/{gymId}/trainers",
                                "/api/v1/gyms/{gymId}/reviews",
                                "/api/v1/gyms/{gymId}/location",
                                "/api/v1/gyms/{gymId}/save",
                                "/api/v1/reservations",
                                "/api/v1/reservations/lessons",
                                "/api/v1/reservations/trainers",
                                "/api/v1/reservations/times",
                                "/api/v1/reservations/rules",
                                "/api/v1/reservations/preview",
                                "/api/v1/reservations/my",
                                "/api/v1/reservations/{id}",
                                "/api/v1/reservations/widget",
                                "/api/v1/reservations/cancel-reasons",
                                "/api/v1/reservations/sessions/{sessionId}/cancel",
                                "/api/v1/reservations/gyms/{id}/status",
                                "/api/v1/gyms",
                                "/api/v1/gyms/count",
                                "/api/v1/gyms/count/by-type",
                                "/api/v1/gyms/count/by-category",
                                "/api/v1/gyms/count/by-subscription",
                                "/api/v1/gyms/count/by-gender",
                                "/api/v1/gyms/entrance/scan",
                                "/api/v1/gyms/entrance/eligibility",
                                "/api/v1/stores",
                                "/api/v1/stores/{storeId}",
                                "/api/v1/stores/{storeId}/location",
                                "/api/v1/stores/{storeId}/save",
                                "/api/v1/catalog/gyms").uri("http://catalog-backend:8080"))

                        .route("storage-backend", r -> r.path(
                                        "/api/v1/media/stream/{fsId}")
                                .uri("http://storage-backend:8080"))

                        .route("notifications-backend", r -> r.path(
                                        "/api/v1/notifications/unread-count",
                                        "/api/v1/notifications",
                                        "/api/v1/notifications/{id}/read",
                                        "/api/v1/notifications/read-all",
                                        "/api/v1/notifications/{id}",
                                        "/api/v1/notifications/all",
                                        "/api/v1/devices/register",
                                        "/api/v1/devices/user/{userId}",
                                        "/api/v1/devices/send",
                                        "/api/v1/sms/send",
                                        "/api/v1/sms/balance",
                                        "/api/v1/sms/report/{transactionId}",
                                        "/api/v1/admin/notifications/broadcast",
                                        "/api/v1/admin/notifications/send",
                                        "/api/v1/admin/notifications/bulk",
                                        "/api/v1/admin/notifications/sms/bulk",
                                        "/api/v1/admin/notifications/email/bulk",
                                        "/api/v1/admin/devices",
                                        "/api/v1/admin/devices/user/{userId}",
                                        "/api/v1/admin/devices/send",
                                        "/api/v1/admin/devices/{deviceId}")
                                .uri("http://notifications-backend:8080"))

                        .route("payment-backend", r -> r.path(
                                "/api/v1/admin/reports/income",
                                "/api/v1/admin/reports/analytics",
                                "/api/v1/admin/transfers/request",
                                "/api/v1/admin/transfers/history",
                                "/api/v1/me/payments/history",
                                "/api/v1/me/payments/history/{transactionId}",
                                "/api/v1/me/payments/order/{orderId}",
                                "/api/v1/me/cards/default",
                                "/api/v1/me/cards/{cardId}",
                                "/api/v1/me/cards",
                                "/api/v1/admin/payments",
                                "/api/v1/admin/payments/{paymentId}",
                                "/api/v1/admin/payments/order/{orderId}",
                                "/api/v1/admin/payments/transaction/{transactionId}",
                                "/api/v1/admin/payments/user/{userId}/history",
                                "/api/v1/coins/wallet",
                                "/api/v1/coins/terms",
                                "/api/v1/coins/history",
                                "/api/v1/coins/calculate-discount",
                                "/api/v1/coins/checkout/preview",
                                "/api/v1/coins/pay-full",
                                "/api/v1/coins/balance",
                                "/api/v1/coins/welcome-bonus/popup-shown",
                                "/api/v2/coins/balance",
                                "/api/v2/coins/full-payment-eligibility",
                                "/api/v1/admin/coins/settings",
                                "/api/v1/admin/coins/terms",
                                "/api/v1/admin/coins/adjust",
                                "/api/v1/admin/coins/bulk-adjust",
                                "/api/v1/admin/coins/bulk-adjust-all",
                                "/api/v1/admin/coins/bulk-welcome-bonus",
                                "/api/v1/admin/coins/history",
                                "/api/v2/admin/coins/settings",
                                "/api/v2/admin/coins/earn/preview",
                                "/api/v2/admin/coins/earn/preview-batch",
                                "/api/heartbeat",
                                "/api/v1/payments/google-pay/create",
                                "/api/v1/payments/google-pay/submit",
                                "/api/v1/payments/apple-pay/create",
                                "/api/v1/payments/apple-pay/submit",
                                "/api/v1/payments/apple-pay/session",
                                "/api/v2/payment/google-pay/create",
                                "/api/v2/payment/google-pay/submit",
                                "/api/v2/payment/apple-pay/create",
                                "/api/v2/payment/apple-pay/submit",
                                "/api/v1/payment/with-card",
                                "/api/v2/payment/epoint/init",
                                "/api/v2/payment/epoint/save-and-pay",
                                "/api/v2/payment/epoint/with-card",
                                "/api/v2/payment/epoint/widget-url",
                                "/api/v2/payment/abb/init",
                                "/api/v2/payment/abb/installment",
                                "/api/v2/payment/bob/init",
                                "/api/v2/payment/bob/pay-with-card",
                                "/api/v2/payment/abb/bnpl/init",
                                "/payment/result",
                                "/payment/callback",
                                "/payment/epoint/callback",
                                "/epoint/result",
                                "/payment/payment/init",
                                "/payment/payment/status/{orderId}",
                                "/payment/card/save-init",
                                "/payment/payment/with-card",
                                "/payment/payment/save-and-pay",
                                "/payment/refund",
                                "/payment/reverse",
                                "/payment/payment/split-init",
                                "/payment/split/with-card",
                                "/payment/payment/split-save-and-pay",
                                "/payment/pre-auth-request",
                                "/payment/pre-auth-complete",
                                "/payment/widget-url",
                                "/payment/wallet/status",
                                "/payment/wallet/pay",
                                "/payment/invoice/create",
                                "/payment/invoice/update",
                                "/payment/invoice/view/{id}",
                                "/payment/invoice/list",
                                "/payment/invoice/send-sms/{id}",
                                "/payment/invoice/send-email/{id}",
                                "/payment/abb/init",
                                "/payment/abb/installment",
                                "/payment/abb/callback",
                                "/payment/abb/redirect/success",
                                "/payment/abb/redirect/success/{orderId}",
                                "/payment/abb/redirect/error",
                                "/payment/abb/redirect/error/{orderId}",
                                "/payment/abb/action/complete",
                                "/payment/abb/action/reverse-online",
                                "/payment/abb/action/reverse-offline",
                                "/payment/abb/action/status/{orderId}",
                                "/payment/abb/bnpl/init",
                                "/payment/abb/bnpl/terms",
                                "/payment/abb/bnpl/status/{id}",
                                "/payment/abb/bnpl/callback",
                                "/payment/abb/bnpl/{id}/reverse",
                                "/payment/abb/bnpl/{id}/partial-reverse",
                                "/payment/bob/init",
                                "/payment/bob/pay-with-card",
                                "/payment/bob/callback",
                                "/payment/bob/status/{orderId}",
                                "/payment/bob/installment",
                                "/payment/bob/cards",
                                "/payment/bob/cards/{cardId}",
                                "/payment/bob/refund",
                                "/payment/redirect/success/{id}",
                                "/payment/redirect/error/{id}",
                                "/payment/heartbeat",
                                "/.well-known/jwks.json",
                                "/payment/.well-known/jwks.json").uri("http://payment-backend:8080"))

                        .route("support-backend", r -> r.path(
                                "/api/v1/admin/faqs",
                                "/api/v1/admin/faqs/{id}",
                                "/api/v1/admin/faq-categories",
                                "/api/v1/admin/faq-categories/{id}",
                                "/api/v1/admin/support/tickets",
                                "/api/v1/admin/support/tickets/{id}/status",
                                "/api/v1/admin/support/contact-details",
                                "/api/v1/support/contactDetails",
                                "/api/v1/public/landing/contact",
                                "/api/v1/public/landing/contact-messages",
                                "/api/v1/public/landing/faqs",
                                "/api/v1/faqs",
                                "/api/v1/faq-categories",
                                "/api/v1/tickets",
                                "/api/v1/tickets/{id}").uri("http://support-backend:8080"))

                        .route("fitness-plan-backend", r -> r.path(
                                "/api/v1/nutrition-plans/**",
                                "/api/v1/workout-plans/**").uri("http://fitness-plan-backend:8080"))

                        .route("order-backend", r -> r.path(
                                "/api/v1/admin/reports/subscriptions",
                                "/api/v1/subscription-packages/**",
                                "/api/v3/subscription-packages",
                                "/api/v3/subscription-packages/**",
                                "/api/v1/me/subscriptions/**",
                                "/api/v2/me/subscriptions/**",
                                "/api/v3/me/subscriptions/**",
                                "/api/v1/subscriptions/upgrade/**",
                                "/api/v1/orders/**",
                                "/api/v1/admin/subscriptions/users/{userId}/current",
                                "/api/v1/admin/subscriptions/users/{userId}/current/entry-limit",
                                "/api/v1/admin/subscriptions/**",
                                "/api/v1/admin/plans/**",
                                "/api/v1/admin/subscription-packages",
                                "/api/v1/admin/subscription-packages/paged",
                                "/api/v1/admin/subscription-packages/names",
                                "/api/v1/admin/subscription-packages/ids",
                                "/api/v1/admin/subscription-packages/options",
                                "/api/v1/admin/subscription-packages/{packageId}",
                                "/api/v1/admin/subscription-packages/{packageId}/options",
                                "/api/v1/admin/subscription-packages/{packageId}/options/{optionId}",
                                "/api/v1/admin/subscription-packages/{packageId}/options/{optionId}/status",
                                "/api/v1/admin/subscription-packages/basic",
                                "/api/v1/admin/subscription-packages/translations",
                                "/api/v1/admin/subscription-packages/translations/bulk",
                                "/api/v1/admin/subscription-packages/**",
                                "/admin/subscription/**").uri("http://order-backend:8080"))
 
                        .route("user-backend", r -> r.path(
                                "/api/v1/admin/reports/users",
                                "/api/v1/admin/goals",
                                "/api/v1/admin/dashboard/kpi-summary",
                                "/api/v1/admin/dashboard/customer-growth",
                                "/api/v1/admin/goals/{code}",
                                "/api/v1/bmi/calculate",
                                "/api/v1/public/landing/goals",
                                "/api/v1/public/landing/goals/{code}",
                                "/api/v1/public/landing/goals/images/{fsId}",
                                "/api/v1/recent-searches",
                                "/api/v1/recent-searches/all",
                                "/api/v1/goals",
                                "/api/v1/goals/{code}",
                                "/api/v1/goals/images/{fsId}",
                                "/api/v1/languages",
                                "/api/v1/languages/{code}",
                                "/api/v1/translations",
                                "/api/v1/translations/bulk",
                                "/api/v1/translations/{entityType}/{entityId}",
                                "/api/v1/admin/users",
                                "/api/v1/admin/users/{userId}",
                                "/api/v1/admin/users/statistics",
                                "/api/v1/translations/goals",
                                "/api/v1/translations/gender",
                                "/api/v1/me/summary",
                                "/api/v1/me",
                                "/api/v2/me",
                                "/api/v1/me/location",
                                "/api/v1/me/body",
                                "/api/v1/me/profile-image",
                                "/api/v1/me/goal",
                                "/api/v1/me/preferences",
                                "/api/v1/me/language",
                                "/api/v1/me/languages",
                                "/api/v1/me/setup",
                                "/api/v1/me/setup/complete",
                                "/api/v1/me/setup/skip",
                                "/api/v1/me/fitness-level",
                                "/api/v1/me/profile/images/{fsId}",
                                "/api/v1/users/profile").uri("http://user-backend:8080"))

                        .route("argocd", r -> r
                                .path("/api/v1/applications/**", "/api/v1/stream/applications/**")
                                .uri("http://argocd-server.argocd.svc:8080"))

                        .route("identity-openapi",
                                r -> r.path("/v3/api-docs/identity-backend")
                                        .filters(f -> f.setPath("/v3/api-docs"))
                                        .uri("http://identity-backend:8080"))
                        .route("catalog-openapi",
                                r -> r.path("/v3/api-docs/catalog-backend")
                                        .filters(f -> f.setPath("/v3/api-docs"))
                                        .uri("http://catalog-backend:8080"))
                        .route("notifications-openapi",
                                r -> r.path("/v3/api-docs/notifications-backend")
                                        .filters(f -> f.setPath("/v3/api-docs"))
                                        .uri("http://notifications-backend:8080"))
                        .route("payment-openapi",
                                r -> r.path("/v3/api-docs/payment-backend")
                                        .filters(f -> f.setPath("/v3/api-docs"))
                                        .uri("http://payment-backend:8080"))
                        .route("support-openapi",
                                r -> r.path("/v3/api-docs/support-backend")
                                        .filters(f -> f.setPath("/v3/api-docs"))
                                        .uri("http://support-backend:8080"))
                        .route("user-openapi",
                                r -> r.path("/v3/api-docs/user-backend")
                                        .filters(f -> f.setPath("/v3/api-docs"))
                                        .uri("http://user-backend:8080"))
                        .route("fitness-plan-openapi",
                                r -> r.path("/v3/api-docs/fitness-plan-backend")
                                        .filters(f -> f.setPath("/v3/api-docs"))
                                        .uri("http://fitness-plan-backend:8080"))
                        .route("order-openapi",
                                r -> r.path("/v3/api-docs/order-backend")
                                        .filters(f -> f.setPath("/v3/api-docs"))
                                        .uri("http://order-backend:8080"))
                        .build();
        }

        public static void main(String[] args) {
                SpringApplication.run(ApiGatewayApplication.class, args);
        }

}