server:
  port: 8080
  forward-headers-strategy: framework
  http2:
    enabled: ${SERVER_HTTP2_ENABLED:true}
  compression:
    enabled: true
    mime-types: application/json,text/plain,text/css,application/javascript,application/openapi+json
    min-response-size: 2048

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: gateway-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  main:
    web-application-type: reactive
    lazy-initialization: false
  messages:
    encoding: UTF-8
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:${REDIS_HOST:redis}}
      port: ${SPRING_DATA_REDIS_PORT:${REDIS_PORT:6379}}
      password: ${SPRING_DATA_REDIS_PASSWORD:}
      timeout: ${SPRING_DATA_REDIS_TIMEOUT:${REDIS_TIMEOUT:2000ms}}
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 2
          max-wait: 2000ms
        shutdown-timeout: 100ms
  codec:
    max-in-memory-size: 1000MB

  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 15s
    vault:
      enabled: ${SPRING_CLOUD_VAULT_ENABLED:false}
      uri: ${SPRING_CLOUD_VAULT_URI:http://127.0.0.1:8200}
      authentication: ${SPRING_CLOUD_VAULT_AUTHENTICATION:TOKEN}
      token: ${VAULT_TOKEN:}
      kv:
        enabled: true
        backend: ${SPRING_CLOUD_VAULT_KV_BACKEND:secrets}
        default-context: ${SPRING_CLOUD_VAULT_KV_DEFAULT_CONTEXT:gateway-backend}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

springdoc:
  api-docs:
    enabled: true
  pre-loading-enabled: true
  swagger-ui:
    use-root-path-mapping: true
    urls:
      - url: /v3/api-docs/identity-backend
        name: identity-backend
      - url: /v3/api-docs/catalog-backend
        name: catalog-backend
      - url: /v3/api-docs/notifications-backend
        name: notifications-backend
      - url: /v3/api-docs/payment-backend
        name: payment-backend
      - url: /v3/api-docs/support-backend
        name: support-backend
      - url: /v3/api-docs/user-backend
        name: user-backend
      - url: /v3/api-docs/fitness-plan-backend
        name: fitness-plan-backend
      - url: /v3/api-docs/order-backend
        name: order-backend

fitnest:
  landing:
    api-key: ${LANDING_API_KEY:}

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: WARN
    org.springframework.cloud: WARN
    org.springframework.security: WARN
    org.springframework.boot: WARN
    az.fitnest.gateway: INFO